services:

  opcua-client:
    image: ghcr.io/wesleyconde/web-opc-ua-client:main
    container_name: OpcUaClient
    ports:
      - 2002:2002
    networks:
      - default

networks:
  default:
    name: coleta-network